# Generated by Django 3.1.3 on 2020-12-13 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='M10Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_num', models.IntegerField()),
                ('issue_date', models.DateField()),
                ('applicator', models.CharField(max_length=50)),
                ('item_type', models.CharField(choices=[('SA', 'معاش'), ('PA', 'مسافرت'), ('PU', 'خریداری')], max_length=2)),
                ('amount', models.IntegerField()),
                ('descript', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='M11Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_num', models.IntegerField()),
                ('issued_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='M3Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_order_num', models.IntegerField()),
                ('issued_date', models.DateField()),
                ('purchase_suggestion_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='M7Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_num', models.IntegerField()),
                ('issued_date', models.DateField()),
                ('order_num', models.IntegerField()),
                ('purchase_place', models.CharField(default='بازار هرات', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SuggestionForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('issued_date', models.DateField()),
                ('deanship', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('dean', models.CharField(max_length=30)),
                ('dean_commandment', models.TextField()),
                ('addminstartion_commandment', models.TextField()),
                ('advice_commitee', models.TextField()),
                ('addminstration_final', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='M7FormDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('module', models.CharField(choices=[('P', 'قطی'), ('C', 'کارتن'), ('N', 'عدد')], max_length=1)),
                ('description', models.CharField(max_length=100)),
                ('observations', models.CharField(max_length=60)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='input.m7form')),
            ],
        ),
        migrations.AddField(
            model_name='m7form',
            name='suggestion_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='input.suggestionform'),
        ),
        migrations.CreateModel(
            name='M3FormDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('item', models.CharField(max_length=30)),
                ('quantity', models.IntegerField()),
                ('module', models.CharField(choices=[('P', 'قطی'), ('C', 'کارتن'), ('N', 'عدد')], max_length=1)),
                ('price', models.IntegerField()),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='input.m3form')),
            ],
        ),
        migrations.AddField(
            model_name='m3form',
            name='suggestion_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='input.suggestionform'),
        ),
        migrations.CreateModel(
            name='M11FormDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
                ('expenses', models.IntegerField()),
                ('dedicated', models.CharField(max_length=50)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='input.m11form')),
            ],
        ),
    ]
