# Generated by Django 3.1.7 on 2021-04-30 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0003_auto_21200213_0629'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='m10form',
            options={'verbose_name': 'فورم 10', 'verbose_name_plural': 'فورم م 10'},
        ),
        migrations.AlterModelOptions(
            name='m11form',
            options={'verbose_name': 'فورم 11', 'verbose_name_plural': 'فورم م 11'},
        ),
        migrations.AlterModelOptions(
            name='m3form',
            options={'verbose_name': 'فورم 3', 'verbose_name_plural': 'فورم م 3'},
        ),
        migrations.AlterModelOptions(
            name='m7form',
            options={'verbose_name': 'فورم 7', 'verbose_name_plural': 'فورم م 7'},
        ),
        migrations.AlterModelOptions(
            name='suggestionform',
            options={'verbose_name': 'فورم پیشنهاد', 'verbose_name_plural': 'فورم پیشنهاد'},
        ),
    ]
