# Generated by Django 3.1.7 on 2021-05-02 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0004_auto_20210430_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='m7formdetail',
            name='amount',
            field=models.IntegerField(default=1, verbose_name='مبلغ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='m7formdetail',
            name='fiyat',
            field=models.IntegerField(default=1, verbose_name='فیات'),
            preserve_default=False,
        ),
    ]
